### PR TITLE
imx_hab4: sign-file: for SPL use CSF_SELF to calculate HAB_LEN

### PR DESCRIPTION
**Pull request by mike-scott**
This allows for the end of the binary to have a placeholder pad
for the CSF area.

For instance, IMX6/7 do not have this padding, but IMX8M does.

NOTE: This patch is no longer needed for i.MX8MM and i.MX8MQ:
https://github.com/foundriesio/meta-lmp/blob/main/meta-lmp-bsp/dynamic-layers/freescale-layer/recipes-bsp/imx-mkimage/imx-boot/0001-iMX8M-support-SPL-ddr-sign.patch

Signed-off-by: Michael Scott <mike@foundries.io>

### CODE REVIEW

**Review by Tim-Anderson — CHANGES_REQUESTED** [review]
Initial test with 6ull on a closed device and the mfgtool SPL.signed file does not work

**Review by Tim-Anderson — COMMENTED** [review]
further testing shows that although the mfgtool SPL.signed fails, the normal SPL.signed appears to work

**Comment by ricardosalveti** [comment]
Change looks OK but we need to test on every target we support:
- apalis-imx6
- apalis-imx8
- imx6ullevk
- imx7ulpea-ucom
- imx8mm-lpddr4-evk
- imx8mq-evk
- imx8qm-mek
- imx8mp-lpddr4-evk

**Comment by MrCry0** [comment]
@ricardosalveti I'll test apalis-imx6/imx8, imx6ullevk, and imx8mm tomorrow morning.

**Comment by MrCry0** [comment]
- apalis-imx6: OK (the patch works well, but the full test is impossible due to other regression bugs in FB and fiovb)
- apalis-imx8: FAIL: CST raises an error
```
Invalid Block arguments, Blocks start offset and length together exceed file size in command AuthenticateData
```

**Comment by vanmaegima** [comment]
This change shouldn't impact:
- apalis-imx8
- imx8qm-mek
As these use AHAB instead of HABv4.

**Comment by vanmaegima** [comment]
CLOSED imx6ull: **FAIL**
SPL-mfgtool.signed fails for a closed imx6ull

**Comment by mike-scott** [comment]
V2 change to fix the DCD_CLEAR behavior:
```
diff --git a/security/imx_hab4/sign-file.sh b/security/imx_hab4/sign-file.sh
index d5e40ee..18d7572 100755
--- a/security/imx_hab4/sign-file.sh
+++ b/security/imx_hab4/sign-file.sh
@@ -288,7 +288,9 @@ ${CST_BINARY} --o ${WORK_FILE}_csf.bin --i ${CSF_TEMPLATE}.csf-config > $OUT
 if [ "${SIGN_M4APP}" = "1" ]; then
     cat ${WORK_FILE}.mod ${WORK_FILE}_csf.bin > ${WORK_FILE}.signed
 else
-    cp ${WORK_FILE}.mod ${WORK_FILE}.signed
+    # We use the *.mod file in the the csf-config (in case we needed to clear the DCD info).
+    # But, we always use the original binary for repackaging with the CSF.
+    cp ${WORK_FILE} ${WORK_FILE}.signed
     dd if=${WORK_FILE}_csf.bin of=${WORK_FILE}.signed seek=$((${HAB_LEN})) bs=1 conv=notrunc
 fi
 echo "Process completed successfully and signed file is ${WORK_FILE}.signed"
 ```

**Comment by mike-scott** [comment]
NOTE: that I've added a comment there to explain why we use the original binary when combining with CSF.bin

**Review by Tim-Anderson — APPROVED** [review]
tested both mfgtool and normal signed SPLs on 6ull and both worked.

LGTM

**Comment by ricardosalveti** [comment]
So devices which requires testing after the new changes:

- apalis-imx6
- imx7ulpea-ucom
- imx8mm-lpddr4-evk
- imx8qm-mek
- imx8mp-lpddr4-evk

@vanmaegima @MrCry0 if you got some cycles ^^

**Comment by ricardosalveti** [comment]
@mike-scott also please send a meta-lmp pr to drop the patch which won't be required anymore.

**Comment by MrCry0** [comment]
- imx8mm-lpddr4-evk-sec (open, fused):
-- mfgtool SPL:
```
HAB Configuration: 0xf0, HAB State: 0x66
No HAB Events Found!
```
-- regular SPL: in progress
- apalis-imx6-sec (open, fused):
-- mfgtool SPL:
```
HAB Configuration: 0xf0, HAB State: 0x66

--------- HAB Event 1 -----------------
event data:
        0xdb 0x00 0x1c 0x41 0x33 0x18 0xc0 0x00
        0xca 0x00 0x14 0x00 0x02 0xc5 0x1d 0x00
        0x00 0x00 0x0c 0xa8 0x00 0x90 0x70 0x00
        0x00 0x00 0x00 0x04

STS = HAB_FAILURE (0x33)
RSN = HAB_INV_SIGNATURE (0x18)
CTX = HAB_CTX_COMMAND (0xC0)
ENG = HAB_ENG_ANY (0x00)


--------- HAB Event 2 -----------------
event data:
        0xdb 0x00 0x14 0x41 0x33 0x0c 0xa0 0x00
        0x00 0x00 0x00 0x00 0x00 0x90 0x74 0x00
        0x00 0x00 0x00 0x20

STS = HAB_FAILURE (0x33)
RSN = HAB_INV_ASSERTION (0x0C)
CTX = HAB_CTX_ASSERT (0xA0)
ENG = HAB_ENG_ANY (0x00)


--------- HAB Event 3 -----------------
event data:
        0xdb 0x00 0x14 0x41 0x33 0x0c 0xa0 0x00
        0x00 0x00 0x00 0x00 0x00 0x90 0x74 0x20
        0x00 0x00 0x00 0x01

STS = HAB_FAILURE (0x33)
RSN = HAB_INV_ASSERTION (0x0C)
CTX = HAB_CTX_ASSERT (0xA0)
ENG = HAB_ENG_ANY (0x00)


--------- HAB Event 4 -----------------
event data:
        0xdb 0x00 0x14 0x41 0x33 0x0c 0xa0 0x00
        0x00 0x00 0x00 0x00 0x00 0x90 0x80 0x00
        0x00 0x00 0x00 0x04

STS = HAB_FAILURE (0x33)
RSN = HAB_INV_ASSERTION (0x0C)
CTX = HAB_CTX_ASSERT (0xA0)
ENG = HAB_ENG_ANY (0x00)
```
-- regular SPL: in progress...

**Comment by mike-scott** [comment]
@MrCry0 Are you using `--fix-sdp-dcd` option for mfgtools?

**Comment by MrCry0** [comment]
> @MrCry0 Are you using `--fix-sdp-dcd` option for mfgtools?

Yes. That is the issue. My script has mistakenly applied this option to all imx6, not 6ul.

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by mike-scott** [comment]
Related `imx-mkimage` patch drop PR: https://github.com/foundriesio/meta-lmp/pull/606

**Comment by ricardosalveti** [comment]
Merging then, thanks everyone for testing this one.

**Pull request merged**
