### PR TITLE
Zynqmp fpga

### PR DESCRIPTION
**Pull request by ldts**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Can you extend the commit log explaining why you need to select ppk 0 explicitly?

**Comment by ldts** [comment]
um, it is highlighting the fact that we are using ppk0 and not ppk1 (ppk0 is the default anyways so it is not really needed). But instead of letting it be implicit, with this commit I am trying to be more explicit so there are no doubts when burning the PPK eFUSE 0...

**Comment by ricardosalveti** [comment]
> um, it is highlighting the fact that we are using ppk0 and not ppk1 (ppk0 is the default anyways so it is not really needed). But instead of letting it be implicit, with this commit I am trying to be more explicit so there are no doubts when burning the PPK eFUSE 0...

sure, just add this at the body of your commit message :-)

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
