### PR TITLE
security: add support for imx8mn and rename imx7ulp folder

### PR DESCRIPTION
**Pull request by vanmaegima**
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

### CODE REVIEW

**Comment by vanmaegima** [comment]
imx8mn uses the same script as imx8mp instead of imx8m*, so I just renamed the imx8mp folder to imx8mn_imx8mp.
Is this a good approach?

**Review by mike-scott — APPROVED** [review]
I do like that we only need to maintain 1 set of scripts for both MN and MP.  +1.

Looks like we probably need to update this page to mention the other IMX8M SoCs:
https://docs.foundries.io/latest/reference-manual/security/secure-machines.html#generate-the-mfgtools-scripts

I'm not sure if it's clear that `soc` can mean `imx8m` (for both `imx8mm` and `imx8mq`) or `imx8mn_imx8mp` (for both `imx8mn` and `imx8mp`).  Might need a table there to make sure folks have a good idea of where to look.

**Comment by vanmaegima** [comment]
Table covered in https://github.com/foundriesio/docs/pull/429
I took this opportunity and renamed the imx7ulpea-ucom folder to imx7ulp as well in this PR.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Comment by vanmaegima** [comment]
@Tim-Anderson can you merge this PR?

**Pull request merged**
